[versions]
mixin = "0.8.5"
geyser = "2.2.2-SNAPSHOT"
auto-service = "1.0.1"
pack-converter = "3.1-SNAPSHOT"
indra = "3.1.3"
shadow = "7.1.3-SNAPSHOT"
architectury-plugin = "3.4-SNAPSHOT"
architectury-loom = "1.5-SNAPSHOT"
minecraft-version = "1.20.4"

# fabric
fabric-loader = "0.15.7"
fabric-api = "0.91.2+1.20.4"

# neoforge
neoforge-version = "20.4.48-beta"

[libraries]
mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
geyser-api = { group = "org.geysermc.geyser", name = "api", version.ref = "geyser" }
geyser-core = { group = "org.geysermc.geyser", name = "core", version.ref = "geyser" }
geyser-fabric = { group = "org.geysermc.geyser", name = "fabric", version.ref = "geyser" }
auto-service = { group = "com.google.auto.service", name = "auto-service", version.ref = "auto-service" }
pack-converter = { group = "org.geysermc.pack", name = "converter", version.ref = "pack-converter" }
indra = { group = "net.kyori", name  = "indra-common", version.ref = "indra" }
shadow = { group = "com.github.johnrengelman", name = "shadow", version.ref = "shadow" }
architectury-plugin = { group = "architectury-plugin", name = "architectury-plugin.gradle.plugin", version.ref = "architectury-plugin" }
architectury-loom = { group = "dev.architectury.loom", name = "dev.architectury.loom.gradle.plugin", version.ref = "architectury-loom" }

# Fabric
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }

# NeoForge
neoforge = { group = "net.neoforged", name = "neoforge", version.ref = "neoforge-version" }
