[versions]
mixin = "0.8.5"
mixinextras = "0.3.5"
geyser = "2.3.2-SNAPSHOT"
auto-service = "1.0.1"
pack-converter = "3.2.1-SNAPSHOT"
indra = "3.1.3"
shadow = "7.1.3-SNAPSHOT"
architectury-plugin = "3.4.155"
architectury-loom = "1.6.396"
asm = "5.2"

# fabric
fabric-loader = "0.15.11"
fabric-api = "0.97.8+1.20.6"

# neoforge
neoforge-version = "20.6.42-beta"

[libraries]
mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
mixinextras = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinextras" }
geyser-api = { group = "org.geysermc.geyser", name = "api", version.ref = "geyser" }
geyser-core = { group = "org.geysermc.geyser", name = "core", version.ref = "geyser" }
geyser-fabric = { group = "org.geysermc.geyser", name = "fabric", version.ref = "geyser" }
auto-service = { group = "com.google.auto.service", name = "auto-service", version.ref = "auto-service" }
pack-converter = { group = "org.geysermc.pack", name = "converter", version.ref = "pack-converter" }
indra = { group = "net.kyori", name  = "indra-common", version.ref = "indra" }
shadow = { group = "com.github.johnrengelman", name = "shadow", version.ref = "shadow" }
architectury-plugin = { group = "architectury-plugin", name = "architectury-plugin.gradle.plugin", version.ref = "architectury-plugin" }
architectury-loom = { group = "dev.architectury.loom", name = "dev.architectury.loom.gradle.plugin", version.ref = "architectury-loom" }
asm = { group = "org.ow2.asm", name = "asm-debug-all", version.ref = "asm" }

# Fabric
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }

# NeoForge
neoforge = { group = "net.neoforged", name = "neoforge", version.ref = "neoforge-version" }
